name: Version Management

on:
  push:
    branches: [ main ]
    paths:
      - 'llmize/**'
      - 'tests/**'
      - 'setup.py'
      - 'pyproject.toml'
      - 'requirements.txt'

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gitpython semver
      
      - name: Get current version
        id: current_version
        run: |
          python -c "import re; content = open('pyproject.toml').read(); version = re.search(r'version = \"([0-9]+\.[0-9]+\.[0-9]+)\"', content).group(1); print(f'::set-output name=version::{version}')"
      
      - name: Determine version bump
        id: version_bump
        run: |
          git fetch --prune --unshallow || true
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          if [[ $COMMIT_MESSAGE == *"BREAKING CHANGE"* ]] || [[ $COMMIT_MESSAGE == *"major:"* ]]; then
            echo "::set-output name=bump::major"
          elif [[ $COMMIT_MESSAGE == *"feat:"* ]] || [[ $COMMIT_MESSAGE == *"feature:"* ]]; then
            echo "::set-output name=bump::minor"
          else
            echo "::set-output name=bump::patch"
          fi
      
      - name: Calculate new version
        id: new_version
        run: |
          python -c "import semver; current_version = '${{ steps.current_version.outputs.version }}'; bump_type = '${{ steps.version_bump.outputs.bump }}'; new_version = getattr(semver, f'bump_{bump_type}')(current_version); print(f'::set-output name=version::{new_version}')"
      
      - name: Update version
        run: |
          python scripts/update_version.py ${{ steps.new_version.outputs.version }}
      
      - name: Commit version update
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "chore: bump version to ${{ steps.new_version.outputs.version }}"
          git tag -a "v${{ steps.new_version.outputs.version }}" -m "Version ${{ steps.new_version.outputs.version }}"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true 